version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/src
    ports:
      - "7000:7000"
    links:
      - mongo
      - elasticsearch
    tty: true
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/db"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
